"""CFRP-VLN protocol and loop helpers."""

from .adapter import CFRPActionAdapterError, HabitatActionAdapter, HabitatActionCommand
from .branching import (
    BranchContext,
    BranchStep,
    BranchTrace,
    BranchTraceRecorder,
    CFRPBranchingError,
    CounterfactualGroup,
    CriticalStateBaseline,
    EnvironmentInfo,
    EpisodeReference,
    MetricSnapshot,
    NavigationPose,
    TrajectoryPrefix,
    make_trajectory_prefix,
    make_navigation_pose,
)
from .checkpoint import (
    CFRPCheckpoint,
    CFRPCheckpointError,
    RestoredCFRPState,
    capture_cfrp_checkpoint,
    restore_cfrp_checkpoint,
)
from .controller import CFRPController, ControllerStepResult
from .loop import CFRPLoopTurn, run_scripted_cfrp_loop
from .plan_initializer import advance_turn_indices, initialize_plan_from_instruction
from .protocol import (
    CFRPOutput,
    CFRPProtocolError,
    MAX_STAGE1_ACTION_CHUNK,
    PlanPoint,
    PlanState,
    PlanUpdate,
    apply_plan_update,
    parse_cfrp_output,
    validate_output,
)
from .rollout_exchange import (
    Stage1RolloutRequest,
    Stage1RolloutResponse,
    read_request,
    read_response,
    request_path,
    response_path,
    wait_for_response,
    write_request,
    write_response,
)
from .warmup_audit import audit_sft_alignment, audit_stage1_warmup

__all__ = [
    "CFRPController",
    "CFRPActionAdapterError",
    "CFRPCheckpoint",
    "CFRPCheckpointError",
    "CFRPBranchingError",
    "CFRPOutput",
    "CFRPProtocolError",
    "CFRPLoopTurn",
    "BranchContext",
    "BranchStep",
    "BranchTrace",
    "BranchTraceRecorder",
    "ControllerStepResult",
    "CounterfactualGroup",
    "CriticalStateBaseline",
    "EnvironmentInfo",
    "EpisodeReference",
    "HabitatActionAdapter",
    "HabitatActionCommand",
    "MetricSnapshot",
    "MAX_STAGE1_ACTION_CHUNK",
    "NavigationPose",
    "PlanPoint",
    "PlanState",
    "PlanUpdate",
    "RestoredCFRPState",
    "Stage1RolloutRequest",
    "Stage1RolloutResponse",
    "TrajectoryPrefix",
    "apply_plan_update",
    "audit_sft_alignment",
    "audit_stage1_warmup",
    "advance_turn_indices",
    "capture_cfrp_checkpoint",
    "make_trajectory_prefix",
    "make_navigation_pose",
    "initialize_plan_from_instruction",
    "parse_cfrp_output",
    "read_request",
    "read_response",
    "request_path",
    "response_path",
    "run_scripted_cfrp_loop",
    "restore_cfrp_checkpoint",
    "validate_output",
    "wait_for_response",
    "write_request",
    "write_response",
]
